[theme]
primaryColor = "#0176D3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F9"
textColor = "#181818"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
